#!/usr/bin/env php
<?php
const PUP_VERSION = '1.0.0';
define( '__PUP_DIR__', __DIR__ );

call_user_func( function( $version ) {
	if ( ! Phar::running() ) {
	  $local_dir_autoload = __PUP_DIR__ . '/vendor/autoload.php';
	  $autoload = getcwd() . '/vendor/autoload.php';

		if ( ! empty( $GLOBALS['_composer_autoload_path'] ) ) {
			require $GLOBALS['_composer_autoload_path'];
		} elseif ( is_file( $local_dir_autoload ) ) {
			require $local_dir_autoload;
		} elseif ( is_file( $autoload ) ) {
			require $autoload;
		} else {
			fwrite( STDERR,
				'You must set up the project dependencies, run the following commands:' . PHP_EOL .
				'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
				'php composer.phar install' . PHP_EOL
			);
			exit( 1 );
		}
	} else {
		require __PUP_DIR__ . '/vendor/autoload.php';
	}

	$app = new StellarWP\Pup\App( $version );
	$app->run();
}, PUP_VERSION );
