#!/usr/bin/php
<?php
const PUP_VERSION = '1.0.0';
const __PUP_DIR__ = __DIR__;

call_user_func( function( $version ) {
	if ( ! Phar::running() ) {
		if ( is_file( $autoload = getcwd() . '/vendor/autoload.php' ) ) {
			require $autoload;
		} else {
			fwrite( STDERR,
				'You must set up the project dependencies, run the following commands:' . PHP_EOL .
				'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
				'php composer.phar install' . PHP_EOL
			);
			exit( 1 );
		}
	} else {
		include 'phar://pup.phar/vendor/autoload.php';
	}

	$app = new StellarWP\Pup\App( $version );
	$app->run();
}, PUP_VERSION );
