name: Build Phar

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader --ignore-platform-reqs

      - name: Build Phar
        run: composer build-phar

      - name: Upload Phar
        uses: softprops/action-gh-release@v3
        with:
          files: ${{ github.workspace }}/pup.phar
          fail_on_unmatched_files: true
