name: Build Phar

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.0'

      - name: Install dependencies
        run: composer install --optimize-autoloader

      - name: Build Phar
        run: composer build-phar

      - name: Upload Phar
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ${{ github.workspace }}/pup.phar
          asset_name: pup.phar
          asset_content_type: application/octet-stream
